### ISSUE TITLE
Suggestion: Symbolics OpenGenera

### ISSUE THREAD

**Issue by jparris** [shaunlebron/history-of-lisp-editing#6]
* Demo Video - https://www.youtube.com/watch?v=o4-YnLpLgtk
* OS Download link - https://archive.org/download/SymblicsOpenGenera
* Resource on how to setup and run the emulator
    - http://www.advogato.org/person/johnw/diary/12.html
    - https://github.com/VrRm/open-genera-setup-script
    - https://github.com/ynniv/opengenera
And finally an article you might find interesting http://lispm.de/symbolics-lisp-machine-ergonomics

**Comment by shaunlebron** [comment]
Thank you 👍

I filled out the [ZMacs](https://github.com/shaunlebron/history-of-lisp-editing#zmacs) section, and linked to this issue for those interested in running it.
